# Generated by Django 3.1.7 on 2021-03-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Academy_Name', max_length=100)),
                ('status', models.CharField(default='open', max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('booked_court_no', models.IntegerField()),
                ('max_court_no', models.IntegerField()),
            ],
        ),
    ]
