# Generated by Django 3.1.7 on 2021-03-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210310_2042'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academy',
            table='Academies',
        ),
    ]
