# Generated by Django 3.1.7 on 2021-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210310_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='booked_court_no',
        ),
        migrations.RemoveField(
            model_name='academy',
            name='max_court_no',
        ),
        migrations.AddField(
            model_name='academy',
            name='nos',
            field=models.IntegerField(default=1),
        ),
    ]
